travis:
  secure:
    BINSTAR_TOKEN: 1ViJKXW67M/fHsYse+VjnZOFYae7FlAF7+icnQQOhFcA2sx5m/PtgZXdqlno9c56aWnieB2LB52CPcNq2mvqOaERI7mYvzAQIjXzykfRT+dQRhDWOPl1/TdIe8b0o9YATcct/BGy8+H/s50YO9jpx8u9FnPm41IrAs5LXsUggNobfafWpwJzBnOuD+Fk62cYllHRonM2A645bkFzJFVLbIWFBh/GricRQGxM8PZUX4k5hgjolQcGr4AN5e2nTuB4IAvWIVVKTHCxwVMcWnQ0D8+tnBQTBdGGdi4tqg3iLYFm6GR+crtLwvf6LLrlZzDddmX/mFpBCR0imMKo7luGMTy86SQovOlGP9ZbfuY9ppjPG59mHS++9DRAu0iMrV5Z0bOl73bk442NMpLJzIoP0vV2ZDFV9Ke5W6JzVV5tgABxcutYdOh6GHG+/E06ys4rBvviNQba44+ZDKr3RFJZDeiQtuyzyp4h0lo+EYVLKZ+K+hdRXybGfW2HAhrMdh4QJ7EXfm2TEFlHOwcNxfaqqR+SNS2wqYrheBXX+PlG9pwUyILKBnUDPFTwG5Zbw9TukeXF31PqD4BAfe5xn/nP4XtZ0PuBUcI0xfLCRCawIRa2HBJ4ftgx5aiVBiLLUPvK1AI1MeezybAiAWCtvwcHiLDGoBUZRumK6grsD1ibHBY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
