travis:
  secure:
    BINSTAR_TOKEN: umc6d9TFww7IRhEMJoWYrOSF1nUa6zzAMA/8DWusQwjW6tTC2w5cZk8r4gJGzhPUIeCTW7ey0tKWYsdn3Y/vMuuETAn9zEQOmib/RbrwJHlyyC30dx559yOIAv0ThNkgd898kxPIMW29xXOj+D9XxWi5yr4t3FuPECfqdC9GeykJTp3iAbBV7cJqBXT/I0khJVOU2a9sZiSOZtHfcWvFvgm4aFMlauIDVp2OdVVuD+DDaQmL9a2HA41FddA/2vzwfakMpCUKGpeP2m8iCZVjnHQPSUAkY1iLuzIuJbUXh/fZ68+ywHd7yEqzd+2qtsM+bb/b74f5EPeneSXw5iCvw5UhfN754pG5eO32fYK2amG1JweNZHwQCjsClkXk7+jPoA4o5B6FrF6RjaLyAbmvJFcIUqBpQI73u3VfY8ybDgvtLopM4nx4/Ip0QYW5TGVUlPqjya+ZeTMWGjRwkwDjCPfOHeT9pYvCCsA9BITqY+P6DJIey8Mp5OQmLQqZpsA5x2Ww1uDZ3dwz0rt9dYXFVUWkbrfCUcd13GXKwkkswTJ6BCmo15IO9T1DlNoJbBNOAmHhXCZZYtMT9QhzU2/onMkFhzngvcY0cdd9RJ34lnXOjWAMSDbdxvVl3nLp3exlh1WM9e253Q+8JItSZS6z90Ys6FLIP+r5/kmErwc5a+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
