travis:
  secure:
    BINSTAR_TOKEN: uoM8RzrFSRYgNCvrcNjAFh9V1ixzUNE8T7iY5w8Cpq4qPE2MsilIagQTJzYIQGwEB57lspOkfHabAKh5YBkOtdOfNPX3lukVufe2sxVtf0/FgvMlCwTd9bwxct50UckrkWZU44qE6+QC2DC0IkoO1KvNVOjqmkzp3HFSl54QHfN90ZKNurlaSzAvgGVjCxPqE9diaKB7+I3EnlW+eLsTQAzsjYnre5AGmXRP24oDDLKUxreMs/qTOWuCkDMdqFFKnfYlijUkmYSZccttW+BtCyxDnMoXsxJb9TfNi8GPM/ffytsYhdP54cR9b2Sl/YJTpIjPtBuYm+KaxsZZY5D2fcnqV1YcSL8AfbyMhiSYtgB98WJ8UXN2ePoxFkm/8IZ52zcqpxP0YThQfkL/D9oG2uLd3LXefCt7PqXaRYRdxaJwU2S1fZsoGNgHmztOC0QJTbn7NkzuSkJZ7x/Zb/H6+ZqhtN+F5C+sKYwUqt8ix9GWuTBmeq2x3pEWVv2ExfDImEDToaie+2orIEftyKZPdx0eftHu7nEAa26KMUI4+7+MM6JB+9oGqzYRzl89m+JqJ4ngGfA2mXMAwi0Q5i0aFWeVvoVnDrnVhpT0oF0v1oSlbLzLutNQiv13u3znY+ZteDGY7iOcV0bzd5CGUaYxLJyPnBPnSWPZTvVQnMBSulQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
