travis:
  secure:
    BINSTAR_TOKEN: QZJ+q9V4jHDIYTCdu0oEIw8FdzZwRw6a48wmSJrPptS2p0tQrh/GdjqYY5uEtNKYwQsIhG/eDtc6RfjFmJxhJlBGXRKi71/kRf5ufrXdl0Jknhtw/fw27BJ27/gFxraHi3gleSmWbF41StHTr4Dr7/vqDRNwizmHvUcaxH1Ksz+szC0sMDLsLS2s5dLhQIYc2r5VwSH5W4Io+wMtqm5HFS9fBmqzP+R2kzNDQuAhOjNd5Wr1QI3n0NCsaoBcPWqHfLjtZPmQleErUKq/x8QC3rZ7StF3wt7nov9NBM03pmIIDk7oOUQXSoYolQKw6hTQdtSGj6t3mkzW2CuCSS7YWk1IxQzWT025hceLHwLrPHEfFiLPSjKLQHjwLk54BPzuYi3u/WX+vrpk/b9xZcsdaYgERF+NqxYg2LUFaMZMau/ZWdHwPfpLsZvFGTg6FDgugpmR9uQYP+ohjZBXKKS7GhlA4yA/v5D8coZDw4zIlXAaU3ocQw3wC9wVMsCx0eFATCOsjKDlHkEWHteYZcWmAb8Nq79zV3kWuFu+nFmhexPFN85rBNrS+7yfLeH+O1VJJF6VvS0XY5F1qx9K0cMHcol79DHRcq978+lj80sP2bcEjSRuy7q2iCRN6MKdLKbn3FQpdd6qY1KpHZnklM16R8k5cMFlHAp/4HKDqOBAI/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
